name: envsubst-action
description: GitHub Action to substitute environment variables
author: Azeem Sajid <azeem.sajid@gmail.com>

branding:
  icon: code
  color: green

inputs:
  env-files:
    description: List of env files
    required: false
  input-files:
    description: List of input files
    required: true
  variables:
    description: List of variables to substitute
    required: false
  enable-in-place:
    description: Enable/disable in-place substitution
    required: false
    default: 'true'
  enable-dump:
    description: Enable/disable dumping of the substituted/updated files
    required: false
    default: 'false'

runs:
  using: composite
  steps:
  - name: Substitute
    env:
      ENV_FILES: '${{ inputs.env-files }}'
      INPUT_FILES: '${{ inputs.input-files }}'
      ENABLE_IN_PLACE: ${{ inputs.enable-in-place == 'true' }}
      ENABLE_DUMP: ${{ inputs.enable-dump == 'true' }}
    shell: bash
    run: $GITHUB_ACTION_PATH/scripts/substitute.bash
