name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v3

    - name: 'Run {enable-in-place: false, enable-dump: true}'
      uses: ./
      env:
        ENV_VAR0: 'env_val0'
        ENV_VAR1: 'env_val1'
        ENV_VAR2: 'env_val2'
        ENV_VAR3: 'env_val3'
        ENV_VAR4: 'env_val4'
      with:
        env-files: |
          test/test.env
        input-files: |
          test/test.json
          test/test.yaml
        enable-in-place: false
        enable-dump: true

    - name: 'Verify {enable-in-place: false, enable-dump: true}'
      run: |
        diff test/test.json.env test/test.json.expected
        diff test/test.yaml.env test/test.yaml.expected
        git restore .

    - name: 'Run {enable-in-place: true, enable-dump: true}'
      uses: ./
      env:
        ENV_VAR0: 'env_val0'
        ENV_VAR1: 'env_val1'
        ENV_VAR2: 'env_val2'
        ENV_VAR3: 'env_val3'
        ENV_VAR4: 'env_val4'
      with:
        env-files: |
          test/test.env
        input-files: |
          test/test.json
          test/test.yaml
        enable-in-place: true
        enable-dump: true

    - name: 'Verify {enable-in-place: true, enable-dump: true}'
      run: |
        diff test/test.json test/test.json.expected
        diff test/test.yaml test/test.yaml.expected
        git restore .

    - name: 'Run with variables {enable-in-place: false, enable-dump: true}'
      uses: ./
      env:
        ENV_VAR0: 'env_val0'
        ENV_VAR1: 'env_val1'
        ENV_VAR2: 'env_val2'
        ENV_VAR3: 'env_val3'
        ENV_VAR4: 'env_val4'
      with:
        env-files: |
          test/test.env
        input-files: |
          test/test.json
          test/test.yaml
        variables: |
          ENV_VAR0
          ENV_VAR1
        enable-in-place: false
        enable-dump: true

    - name: 'Verify with variables {enable-in-place: false, enable-dump: true}'
      run: |
        diff test/test.json.env test/test-vars.json.expected
        diff test/test.yaml.env test/test-vars.yaml.expected
        git restore .

    - name: 'Run with output-directory {enable-in-place: false, enable-dump: true}'
      uses: ./
      env:
        ENV_VAR0: 'env_val0'
        ENV_VAR1: 'env_val1'
        ENV_VAR2: 'env_val2'
        ENV_VAR3: 'env_val3'
        ENV_VAR4: 'env_val4'
      with:
        env-files: |
          test/test.env
        input-files: |
          test/test.json
          test/test.yaml
        output-directory: ./output
        enable-in-place: false
        enable-dump: true

    - name: 'Verify with output-directory {enable-in-place: false, enable-dump: true}'
      run: |
        diff output/test.json.env test/test.json.expected
        diff output/test.yaml.env test/test.yaml.expected
        git restore .
